version: "3.5"
services: 
  backend:
    container_name: testeBackend
    image: node:12.20.2
    ports: 
      - 81:3333
    volumes: 
      - ${PWD}/backend:/opt/ui
    command: npm run dev
    working_dir: /opt/ui
    user: "1000"
    depends_on: 
      - "sqlserver"
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: sqlserverV2017
    environment:
        SA_PASSWORD: "YOUR_PASSOWORD"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"      
    volumes: 
      - ${PWD}/data/sqlserver:/var/opt/mssql     